name: swimmer_ncap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy<2.0
  - pandas
  - matplotlib=3.8.3
  - seaborn
  - pyyaml
  - tqdm
  - scipy
  - psutil
  - pip
  - pip:
    - dm-control>=1.0.16
    - ffmpeg
    - imageio-ffmpeg
    - opencv-python-headless
    - networkx
    - jupyter
    - ipywidgets
    - ipykernel
